### ISSUE TITLE
Create Backend routes for User Management

### ISSUE THREAD

**Issue by Tugduoff** [AdamLesage/area-epitech#24]
Creating back end routes for user management is very important as well. Theses represent : 

- [x] Get User profile #48 
- [x] Modify User profile #49 
- [x] Delete user #51 
- [x] Create a new user #50 

Each of those can be accessed from the user or an admin POV

For more informations see issue #52
