### ISSUE TITLE
Front end Auth pages

### ISSUE THREAD

**Issue by Tugduoff** [AdamLesage/area-epitech#67]
### Feature description

Those pages need to be done : 

- [x] Sign up 1: Email and Account creation #68 
- [x] Sign up 2: Details retrieval #69 
- [x] Login: Account access #72 
- [x] Email verification Screen #74 
- [x] Forgot Password retrieval page #79 
- [x] Change Password page #81 

### Examples

View the [Figma](https://www.figma.com/design/AX87EN6wRjATgkp9vW6c9O/AREA-Figma?node-id=0-1&node-type=canvas&t=vC7MI5hf93taeVcX-0) for more info.

Screens:

![Email Verification Screen](https://github.com/user-attachments/assets/36d940a5-f465-4b4a-afaf-910672f358fd)
![Login Screen](https://github.com/user-attachments/assets/8e3c0de2-2b91-43e5-83da-d8f3e0e61845)
![Details Screen](https://github.com/user-attachments/assets/c3e3b1cc-bed2-461b-9385-c5f00305afaa)
![Sign Up Screen](https://github.com/user-attachments/assets/427465b6-66b9-4fa6-a483-3479d535d6dc)
![Password Retrieval](https://github.com/user-attachments/assets/f6751f26-5b70-46dd-b3b1-96403cfcf76b)
![Password Change](https://github.com/user-attachments/assets/5a73f5c9-ff55-4b39-8d3c-9a0114427010)

### What is the priority?

1

### What is the approximate size (in terms of work time) of the feature?

L
